version: '3'
services:
  ingestor:
    build: ingestor/.
    ports:
    - "8080:8080"
  recorder:
    build: recorder/.
    command: ["-tweetsURL", "http://ingestor:8080/tweets"]
    ports:
    - "8085:8085"
    volumes:
    - ./recorder/:/data/
    links:
    - ingestor
  stopwordfilter:
    build: stopwordfilter/.
    command: ["-tweetsURL", "http://recorder:8085/tweets"]
    ports:
    - "8081:8081"
    volumes:
    - ./stopwords/:/stopwords/
    links:
    - recorder
  wordcounter:
    build: wordcounter/.
    command: ["-tweetsURL", "http://stopwordfilter:8081/tweets"]
    ports:
    - "8082:8082"
    links:
    - stopwordfilter
  windower:
    build: windower/.
    command: [
      "-wordCountsURL", "http://wordcounter:8082/tweets",
      "-searchesURL", "http://searches:8084/searches"]
    ports:
    - "8083:8083"
    links:
    - wordcounter
    - searches
  searches:
    build: searches/.
    ports:
    - "8084:8084"
    volumes:
    - ./searches/:/data/
    